### ISSUE TITLE
503 Application error.

### ISSUE THREAD

**Issue by mmchougule** [ArchDev/akka-http-rest#6]
I was just trying to go through the code and clicked on the link for live example. It is giving 503 "Application Error". I am facing the same issue on my akka http app on Heroku. Do you know what it might be? Logs are not showing much info on it.

**Comment by ArchDev** [comment]
Currently fixing it, example deployment is broken.

**Comment by ArchDev** [comment]
Fixed.

**Comment by mmchougule** [comment]
@ArchDev how did you fix it? I am seeing the same issue with my akka http example.

**Comment by ArchDev** [comment]
An error was because I not specified Procfile for Heroku. Which kind of error do you have? Are you trying to deploy it on heroku too?

**Comment by mmchougule** [comment]
I am getting this 503 Application Error.

2017-10-24T01:47:29.397112+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=gentle-crag-87651.herokuapp.com request_id=58316117-8c4b-4d29-8341-b3f978330380 fwd="24.147.6.164" dyno= connect= service= status=503 bytes= protocol=https
2017-10-24T01:47:29.702207+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=gentle-crag-87651.herokuapp.com request_id=67889b17-2565-44de-900c-3b75b74510f4 fwd="24.147.6.164" dyno= connect= service= status=503 bytes= protocol=https


I will check to see how I can specify a Procfile for Heroku.

**Comment by ArchDev** [comment]
https://github.com/ArchDev/akka-http-rest/commit/9c304379bc4d5696510fe317d2fe2a9df265cf90

Also don't forget to pass ENV variables with postgres connection properties

**Comment by mmchougule** [comment]
@ArchDev thank you. That helped.

Now I am getting this:
Starting process with command `target/universal/stage/bin/akka-http -Dhttp.port=${PORT}`

Then it is able to start the server. But I get this. I am not sure why because I have PORT set to 8080 in env. 
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch.

**Comment by ArchDev** [comment]
If you have environment variables JDBC_URL, JDBC_USER, JDBC_PASSWORD configured in Heroku and your repo looks exactly like original, then everything should work.

**Comment by ArchDev** [comment]
-Dhttp.port overrides port in config, if you don't use port from config, then probably you will have problems with deployment.

**Comment by mmchougule** [comment]
@ArchDev thank you for helping me out. Sorry, I am new to akka http. I had to replace "localhost" to "0.0.0.0" in Http().bindAndHandle(). It works now. :)
