### ISSUE TITLE
How to fix Slick Exception of single AutoInc column returned on INSERT

### ISSUE THREAD

**Issue by spbaniya** [ArchDev/akka-http-rest#7]
I tried to implement the akka-http rest example provided at
[https://github.com/ArchDev/akka-http-rest][1]
 but I'm stuck with the     

        slick.SlickException: This DBMS allows only a single column to be returned from an INSERT, and that column must be an AutoInc column.
        at slick.jdbc.JdbcStatementBuilderComponent$JdbcCompiledInsert.buildReturnColumns(JdbcStatementBuilderComponent.scala:67)

Here is the Scala Code:
Signup API:

    path("signUp") {
        pathEndOrSingleSlash {
          post {
            entity(as[UsernamePasswordEmail]) { userEntity =>
              complete(Created -> signUp(userEntity.username, userEntity.email, userEntity.password))
            }
          }
        }
      }

AuthService.scala

    def signUp(login: String, email: String, password: String): Future[AuthToken] =
        authDataStorage
          .saveAuthData(AuthData(UUID.randomUUID().toString, login, email, password.sha256.hex))
          .map(authData => encodeToken(authData.id))

AuthDataStorage.scala

    ...
    override def saveAuthData(authData: AuthData): Future[AuthData] =
        db.run((auth returning auth).insertOrUpdate(authData)).map(_ => authData)
    ...

Since I'm new to Scala and Slick, can anyway provide the information why this exception is occurring even though I've defined `O.AutoInc` in Model. I'm using MySQL RDBMS

  [1]: https://github.com/ArchDev/akka-http-rest

**Comment by ArchDev** [comment]
Hey, thanks for notice, MySQL don't support returning of entity after saving, there is a fix:
https://github.com/ArchDev/akka-http-rest/commit/4adf71c157ad73b1e507fcafd602d46d4c5b0dd4

**Comment by luiscarbonel1991** [comment]
> Hey, thanks for notice, MySQL don't support returning of entity after saving, there is a fix: [4adf71c](https://github.com/arhelmus/akka-http-rest/commit/4adf71c157ad73b1e507fcafd602d46d4c5b0dd4)

Hi, you can try with this code (Work for me):
  (auth returning auth.map(_.id)
                into ((data, id) => data.copy(id=id))
                ) += authData
